#!/bin/bash

BAR_FIFO=/tmp/bspwm_bar_fifo
BAR_WM_NAME="bspwm_bar"
DIRNAME=$(dirname $0)


if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "${BAR_FIFO}" ] && rm "${BAR_FIFO}"
mkfifo "${BAR_FIFO}"

bspc subscribe report > "$BAR_FIFO" &

while true;
do
  ACPI=$(acpi --battery)
  PERC=$(echo "${ACPI}" | cut -d, -f2 | tr -d ' ')
  DISCHARGING=$(echo "${ACPI}" | grep -c Discharging)
  echo "BAT${DISCHARGING},${PERC}"
  sleep 5;
done > "$BAR_FIFO" &

while true;
do
  VOL=$(amixer sget Master | tail -1 | sed -re 's/.*\[([0-9]+)%\].*\[(on|off)\]/\2!\1/')
  echo "VOL$VOL"
  sleep 1
done > "$BAR_FIFO" &

while true;
do
  TIME=$(date +"%H:%M")
  echo "TIM$TIME"
  sleep 45
done > "$BAR_FIFO" &

while true;
do
  spotify_status=$(playerctl -p spotify status)
  if [ $spotify_status != "Not available" ]
  then
    music_title=$(playerctl -p spotify metadata title)
    music_artist=$(playerctl -p spotify metadata artist)
    music_data="${music_artist} - ${music_title}"
  else
    music_data="NA"
  fi
  echo "MUS$music_data"
  sleep 5
done > "$BAR_FIFO" &

. ~/.cache/wal/colors.sh

cat "${BAR_FIFO}" | $DIRNAME/panel_bar | lemonbar -g "x25" -B "${color0}" -F "${color7}" -f "Iosevka Term-10" -f "Font Awesome-10" | bash &

wait
