#!/bin/bash

#num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		DAT*)
			# clock output
			date="${line#???}"
			;;
		BAT*)
			# battery capacity
			_line=(${line#???})
			discharging=(${_line%%,*})
			echo ${line} >> /tmp/ouioui.txt
			if [ "$discharging" -eq 1 ] ; then
				icon='\uf241'
			else
				icon='\uf1e6'
			fi
			level="${_line##*,}"
			bat="${icon} ${level}"
			;;
		VOL*)
			# volume level
			_line=(${line#???})
			vol="${_line}"
			;;
	esac
	echo -e "%{c}${date}%{r} ${bat} \uf028 ${vol} "
done
