#!/bin/bash

#num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		DAT*)
			# clock output
			date="${line#???}"
			;;
		BAT*)
			# battery capacity
			_line=(${line#???})
			discharging=(${_line%%,*})
			if [ "$discharging" -eq 1 ] ; then
				icon='\uf241'
			else
				icon='\uf1e6'
			fi
			level="${_line##*,}"
			bat="${icon} ${level}"
			;;
		VOL*)
			# volume level
			_line=(${line#???})
			sound=${_line%%!*}
			level=${_line##*!}
			if [ "$sound" == "off" ] ; then
				icon='\uf026'
			else
				icon='\uf028'
			fi
			vol="${icon} ${level}%"
			# volume-off: f026
			# volume-down: f027
			# volume-up: f028
			;;
		W*)
			# bspc report
			wm=
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[fFoOuU]*)
						# square:f0c8 square-o:f096
						# circle:f111 circle-o:f10c circle-dot:f192
						case $item in
							f*)
								# free/occupied/urgent desktop
								str="\uf10c"
								;;
							o*)
								# focused free/occupied/urgent desktop
								str="\uf192"
								;;
							u*)
								# focused free/occupied/urgent desktop
								str="\uf096"
								;;
							[FOU]*)
								# focused free/occupied/urgent desktop
								str="\uf111"
								;;
						esac
						wm="${wm} %{A:bspc desktop -f ${name}:}${str}%{A} "
				esac
				shift
			done
			;;
	esac
	echo -e "%{l} ${wm}%{c}${date}%{r}${bat} ${vol} "
done
