#!/bin/bash

#num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		DAT*)
			# clock output
			date="${line#???}"
			;;
		BAT*)
			# battery capacity
			_line=(${line#???})
			bat="${_line}"
			;;
		VOL*)
			# volume level
			_line=(${line#???})
			vol="${_line}"
			;;
	esac
	printf "%s\n" "%{c}\uf242 ${date}%{r} \uf241 ${bat} \uf028 ${vol} "
done
