#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5

# source the colorscheme
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a Firefox desktop=^2
bspc rule -a Spotify desktop=^3

dunst -nb ${color0} -nf ${color7} -nfr ${color1} &

~/scripts/lemon_panel &
